font=FiraCode Nerd Font Mono:style=Regular:size=16


# @define-color black #000000;
# @define-color red #c5003c;
# @define-color dark_red #880425;
# @define-color light_yellow #ffff80;
# @define-color yellow #ffff00;
# @define-color aqua #55ead4;
# @define-color green #00ff9f;
# @define-color light_blue #00b8ff;
# @define-color dark_blue #001eff;
# @define-color dark_pink #bd00ff;
# @define-color pink #d600ff;

[colors]
# cursor hover-over color and cursor color
cursor=000000 ffff00 # black / yellow
foreground=ffff00 # text color
background=000000 # dark blue

regular0=ffff00 # greyish don't really know what this is
regular1=c5003c # red, fx error msg in terminal
regular2=00ff9f # green, name of user, executables # 001eff
regular3=f9e2af # sand
regular4=d600ff # pink, directories
regular5=f5c2e7 # light pinkish
regular6=94e2d5 # cyanish
regular7=bac2de # another light blue

bright0=585b70 # only difference from above: greyish
bright1=f38ba8
bright2=a6e3a1
bright3=f9e2af
bright4=89b4fa
bright5=f5c2e7
bright6=94e2d5
bright7=a6adc8

16=fab387 # orangish salmon
17=f5e0dc # nearly white

selection-foreground=000000 # black
selection-background=ffff80 # light_yellow

search-box-no-match=11111b f38ba8 # pinkish
search-box-match=cdd6f4 313244 # same as foreground, bit lighter then selection-background

jump-labels=11111b fab387 # same as cursor, and orange sandy
urls=89b4fa # hyperlink colored

# [colors]
# cursor=11111b f5e0dc # Blackblue / light rosy
# foreground=cdd6f4 # light blue
# background=1e1e2e # dark blue
# 
# regular0=45475a # greyish i think this is highlight
# regular1=f38ba8 # salmon
# regular2=a6e3a1 # light green
# regular3=f9e2af # sand
# regular4=89b4fa # blue
# regular5=f5c2e7 # light pinkish
# regular6=94e2d5 # cyanish
# regular7=bac2de # another light blue
# 
# bright0=585b70 # only difference from above: greyish
# bright1=f38ba8
# bright2=a6e3a1
# bright3=f9e2af
# bright4=89b4fa
# bright5=f5c2e7
# bright6=94e2d5
# bright7=a6adc8
# 
# 16=fab387 # orangish salmon
# 17=f5e0dc # nearly white
# 
# selection-foreground=cdd6f4 # same as foreground
# selection-background=414356 # not as dark blue as background
# 
# search-box-no-match=11111b f38ba8 # pinkish
# search-box-match=cdd6f4 313244 # same as foreground, bit lighter then selection-background
# 
# jump-labels=11111b fab387 # same as cursor, and orange sandy
# urls=89b4fa # hyperlink colored
