font=FiraCode Nerd Font Mono:style=Regular:size=16

# @define-color dark_sand #4e2918;
# @define-color light_sand #e1b39d;
# @define-color medium_sand #c3673c;
# @define-color yellow #ffff00; # for debugging!
# @define-color dark_red #cc0000;
# @define-color dark_green #336600;
# @define-color teal #008080;

[mouse]
hide-when-typing=yes

[colors-dark]
# cursor hover-over color and cursor color
cursor=e1b39d c3673c # black / yellow
foreground=4e2918 # text color
background=e1b39d

regular0=e1b39d # k9s background
regular1=cc0000 # un-committed stuff, not-clean-indicator (little red circle)
regular2=336600 # name of user, executables # 001eff
regular3=c3673c # git branch colors
regular4=4e2918 # directories
regular5=ffff00 #
regular6=008080 # symlinks
regular7=ffff00 #

# AFAIK this is used by k9s, maybe other tuis
# Just reflect regular down here.
bright0=e1b39d
bright1=cc0000
bright2=336600
bright3=c3673c
bright4=4e2918
bright5=ffff00
bright6=008080
bright7=ffff00

16=ffff00 # orangish salmon
17=ffff00 # nearly white

selection-foreground=ffff00 # yellow
selection-background=ffff00 # black

search-box-no-match=ffff00 ffff00 # pinkish
search-box-match=ffff00 ffff00 # same as foreground, bit lighter then selection-background

jump-labels=ffff00 ffff00 # same as cursor, and orange sandy
urls=ffff00 # hyperlink colored
