font=TempleOS:style=Regular:size=16
 

# @define-color black #000000;
# @define-color red #c5003c;
# @define-color dark_red #880425;
# @define-color light_yellow #ffff80;
# @define-color yellow #ffff00;
# @define-color aqua #55ead4;
# @define-color green #00ff9f;
# @define-color light_blue #00b8ff;
# @define-color dark_blue #001eff;
# @define-color dark_pink #bd00ff;
# @define-color pink #d600ff;

[colors-dark]
# cursor hover-over color and cursor color
cursor=ffffff 000000 # white / black
foreground=000000 # text color
background=ffffff # black

regular0=ffff00 # yellow, fx highlight of path on symlinks
regular1=c5003c # red, fx error msg in terminal
regular2=c5003c # green, name of user, executables
regular3=00b8ff # light blue, git branch colors
regular4=d600ff # pink, directories
regular5=f5c2e7 # light pinkish
regular6=c5003c # red, also symlinks?
regular7=bac2de # another light blue

bright0=ffff00 # only difference from above: greyish
bright1=c5003c
bright2=00ff9f
bright3=00b8ff
bright4=d600ff
bright5=f5c2e7
bright6=c5003c
bright7=bac2de

16=d600ff # orangish salmon
17=d600ff # nearly white

selection-foreground=ffff00 # yellow
selection-background=c5003c # black

search-box-no-match=d600ff d600ff # pinkish
search-box-match=d600ff d600ff # same as foreground, bit lighter then selection-background

jump-labels=d600ff d600ff # same as cursor, and orange sandy
urls=89b4fa # hyperlink colored
